### ISSUE TITLE
Ability to dereference schema from a different domain

### ISSUE THREAD

**Issue by Napas** [BigstickCarpet/json-schema-ref-parser#83] opened 2018-05-17 15:47 UTC
Hi,

Is there ability to dereference a schema from a different domain. I.e
```
   {
        "$id": "https://example.com/schema.json",
        "type": "array",
        "other": {
            "type": "array",
            "items": {
                "anyOf": [
                  { "$ref": "other/schema.json" }
                ]
            }
        }
    }
```

```$ref``` should resolve to the ```http://example.com/other/schema.json``` independently on current URL it is running.

Is there a way to set a base URL where it should look for the schemas?

**Comment by BigstickCarpet** [comment] 2018-05-23 11:52
JSON Schema $Ref Parser is an implementation of the [JSON Reference specification](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03) and the [JSON Pointer specification](https://tools.ietf.org/html/rfc6901), _not_ the  [JSON Schema specification](http://json-schema.org/latest/json-schema-core.html).  Thus, the `$id` keyword isn't supported, because that's not part of JSON Reference or JSON Pointer.

I might be willing to add support for the `$id` keyword at some point in the future, if there's enough demand for it.  But I want to hold-off on that for now, because it could be very confusing to start supporting _part_ of the JSON Schema specification but not all of it.

See [**this issue**](https://github.com/BigstickCarpet/json-schema-ref-parser/issues/22) for more details.

**Comment by BigstickCarpet** [comment] 2018-05-23 11:53
I'm closing this issue and marking it as a duplicate of #22 so we can keep any relevant discussion/updates in one place.

**Closed by BigstickCarpet** 2018-05-23 11:53 UTC
Labels: duplicate
